server:
  port: 8082

spring:
  application:
    name: fulfillment-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fulfillment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

fulfillment:
  warehouse-id: WH-BUC-01
  estimated-delivery-days: 3

logging:
  level:
    com.example.fulfillmentservice: DEBUG
